### ISSUE TITLE
RuntimeException: scala.Some is not a valid external type for schema of string

### ISSUE THREAD

**Issue by pisarenko-net** [crealytics/spark-excel#181]
I'm trying to read an Excel file in Java using the `spark-excel` library. It appears that the returned data is wrapped in `scala.Some` type.

Here is how I invoke the library:
```
        Dataset<Row> extractedExcel = sparkSession
                .read()
                .format("com.crealytics.spark.excel")
                .option("inferSchema", "false")
                .option("treatEmptyValuesAsNulls", "false")
                .option("useHeader", "true")
                // .schema(schema)
                .load(absPath);
```
Then, if I make any call on the resulting dataset, say `extractedExcel.show();` or try to write the dataset out, I run into an exception:

```
Caused by: java.lang.RuntimeException: scala.Some is not a valid external type for schema of string
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.StaticInvoke_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:324)
```

The error message suggests that the returned dataset wraps values in a `scala.Some`. I don't see how can the values be unwrapped and turned into plain strings.

**Comment by nightscape** [comment]
Could you try the same example in Scala (e.g. in a `spark-shell`) to see if the same error happens?

**Comment by pisarenko-net** [comment]
I suppose the problem is due to the fact that the values are wrapped into `Option`:
https://issues.apache.org/jira/browse/SPARK-19056

There are a couple of SO issues I found that appear relevant:
 - https://stackoverflow.com/questions/44324195/problems-to-create-dataframe-from-rows-containing-optiont
 - https://stackoverflow.com/questions/41443028/unable-to-create-org-apache-spark-sql-row-with-scala-none-value-since-spark-2-x

Both of these issues refer to SPARK-19056.

I don't know if there's a way for me to unwrap the `Option`s -- it's not clear where would this conversion need to happen.

**Comment by EnverOsmanov** [comment]
@pisarenko-net could you provide a file? I couldn't reproduce the exception. Here is my [code](https://github.com/EnverOsmanov/sbt-assembly_TEST/blob/spark-excel/src/main/java/program/Main.java).

**Comment by jn73** [comment]
We're seeing this problem when trying to run spark-excel with the latest spark 3.0.0-preview2 release. Not sure if this should work with spark 3.0. Anyway, here's a link to the code to reproduce: https://github.com/jn73/spark-excel-bug

**Comment by EnverOsmanov** [comment]
Thanks, @jn73. Your example was very helpful. PR is about to arrive.
Still I couldn't reproduce it with Spark 2.4. I hope the fix will work in both cases.

**Comment by jn73** [comment]
Great @EnverOsmanov. How soon can we expect to see this in a release? Was thinking if i should publish a snapshot in our company repo or just wait.

**Comment by EnverOsmanov** [comment]
I just did a release, should be available very soon (maybe already).

**Comment by jn73** [comment]
@EnverOsmanov i'm not seeing 0.13.3 in maven central or sonatype public. Am i missing something?

**Comment by EnverOsmanov** [comment]
You are right, and 0.13.2 is [missing](https://mvnrepository.com/artifact/com.crealytics/spark-excel) either.
@nightscape, you are more experienced with GitHub Actions - could please you have a look? I think something went wrong in this [commit](https://github.com/crealytics/spark-excel/commit/20021ff99da6389b84f6eb7a8a00e386f8572cc5).

**Comment by nightscape** [comment]
Hey @EnverOsmanov, I think I just fixed the release process (it's still running, but looking good): https://github.com/crealytics/spark-excel/runs/949342540?check_suite_focus=true
Github should now publish the artefacts to Maven Central when you create a release.
`0.13.4` is on its way :+1:

**Comment by xvinosh** [comment]
I am still facing the same issue while show and write. Did anyone got the solution.

**Comment by EnverOsmanov** [comment]
@xvinosh , if you could provide a reproducable example, we can have a look.

**Comment by xvinosh** [comment]
> @xvinosh , if you could provide a reproducable example, we can have a look.
