### ISSUE TITLE
support spark 3.5

### ISSUE THREAD

**Issue by melin** [crealytics/spark-excel#787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Spark version:
- Spark-Excel version:
- OS:
- Cluster environment
```

**Comment by nightscape** [comment]
Done in https://github.com/crealytics/spark-excel/pull/784
Release is on its way.

**Comment by dolfinus** [comment]
Still don't see package for Spark 3.5.0 in Maven:
https://mvnrepository.com/artifact/com.crealytics/spark-excel

**Comment by nightscape** [comment]
There was an issue with the publishing step. 0.20.1 is published for Spark 3.5.
